version: "3.9"

services:

  postgres:
    image: postgres:16

    container_name: datosenorden_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: datosenorden
      POSTGRES_USER: datosenorden
      POSTGRES_PASSWORD: datosenorden

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: