from __future__ import annotations


def get_guided_questions() -> dict[str, object]:
    return {
        "questions": [
            {
                "id": "who_sells_to_this_body",
                "title": "¿Quién vende a este organismo?",
                "description": "Explora proveedores y compras públicas asociadas a una entidad.",
                "concepts": ["Organismo", "Proveedor", "Contrato"],
                "suggested_sources": ["ChileCompra", "Registro Empresas"],
                "example_query": "Servicio de Salud Arauco",
                "search_query": "Servicio de Salud Arauco",
                "cta": "Buscar proveedores",
            },
            {
                "id": "which_suppliers_appear",
                "title": "¿Qué proveedores aparecen?",
                "description": "Revisa empresas conectadas con compras públicas o expedientes abiertos.",
                "concepts": ["Proveedor", "Empresa", "Contrato"],
                "suggested_sources": ["ChileCompra", "Registro Empresas"],
                "example_query": "proveedor",
                "search_query": "proveedor",
                "cta": "Buscar proveedores",
            },
            {
                "id": "which_authorities_appear",
                "title": "¿Qué autoridades aparecen?",
                "description": "Explora cargos públicos, nombramientos y periodos electorales.",
                "concepts": ["Persona", "Cargo Público", "Nombramiento"],
                "suggested_sources": ["Diario Oficial", "Transparencia Activa", "SERVEL"],
                "example_query": "autoridad",
                "search_query": "autoridad",
                "cta": "Buscar autoridades",
            },
            {
                "id": "which_official_publications_exist",
                "title": "¿Qué publicaciones oficiales existen?",
                "description": "Revisa nombramientos, renuncias y actos administrativos.",
                "concepts": ["Publicación oficial", "Decreto", "Nombramiento", "Renuncia"],
                "suggested_sources": ["Diario Oficial"],
                "example_query": "Diario Oficial",
                "search_query": "Diario Oficial",
                "cta": "Ver publicaciones",
            },
            {
                "id": "which_meetings_were_recorded",
                "title": "¿Qué reuniones fueron registradas?",
                "description": "Explora reuniones de lobby y sus contrapartes visibles.",
                "concepts": ["Reunión", "Persona", "Organismo"],
                "suggested_sources": ["Lobby", "Transparencia Activa"],
                "example_query": "reuniones de lobby",
                "search_query": "reuniones de lobby",
                "cta": "Buscar reuniones",
            },
            {
                "id": "which_related_companies_exist",
                "title": "¿Qué empresas relacionadas existen?",
                "description": "Busca sociedades, representantes y socios vinculados a una empresa.",
                "concepts": ["Empresa", "Persona", "Representante", "Socio"],
                "suggested_sources": ["Registro Empresas", "ChileCompra"],
                "example_query": "empresa",
                "search_query": "empresa",
                "cta": "Buscar empresas",
            },
        ],
        "categories": [
            {
                "id": "public_organizations",
                "title": "Organismos públicos",
                "description": "Empieza por entidades del Estado y sus cruces visibles.",
                "examples": [
                    "Servicio de Salud Arauco",
                    "Municipalidad ejemplo",
                    "Organismo ejemplo",
                ],
                "suggested_sources": ["ChileCompra", "Lobby", "Diario Oficial"],
                "search_query": "organismo publico",
                "cta": "Explorar organismos",
            },
            {
                "id": "suppliers",
                "title": "Proveedores",
                "description": "Explora empresas que aparecen en compras o registros societarios.",
                "examples": [
                    "Empresa A",
                    "Empresa B",
                    "Consultora Publica SPA",
                ],
                "suggested_sources": ["ChileCompra", "Registro Empresas"],
                "search_query": "empresa",
                "cta": "Explorar proveedores",
            },
            {
                "id": "authorities",
                "title": "Autoridades",
                "description": "Revisa personas vinculadas a cargos y nombramientos.",
                "examples": [
                    "Persona A",
                    "Persona B",
                    "Autoridad ejemplo",
                ],
                "suggested_sources": ["Diario Oficial", "Transparencia Activa", "SERVEL"],
                "search_query": "autoridad",
                "cta": "Explorar autoridades",
            },
            {
                "id": "procurement",
                "title": "Compras",
                "description": "Explora compras, contratos y órdenes visibles.",
                "examples": [
                    "Contrato ejemplo",
                    "Orden de compra ejemplo",
                    "Licitación ejemplo",
                ],
                "suggested_sources": ["ChileCompra", "DIPRES"],
                "search_query": "compra publica",
                "cta": "Explorar compras",
            },
            {
                "id": "budgets",
                "title": "Presupuestos",
                "description": "Busca asignaciones y ejecuciones presupuestarias de muestra.",
                "examples": [
                    "Servicio de Salud Arauco",
                    "Ministerio ejemplo",
                    "Presupuesto ejemplo",
                ],
                "suggested_sources": ["DIPRES", "ChileCompra"],
                "search_query": "presupuesto",
                "cta": "Explorar presupuestos",
            },
            {
                "id": "meetings",
                "title": "Reuniones",
                "description": "Consulta reuniones registradas y sus materias visibles.",
                "examples": [
                    "Reunión A",
                    "Reunión B",
                    "Lobby ejemplo",
                ],
                "suggested_sources": ["Lobby", "Transparencia Activa"],
                "search_query": "reunion",
                "cta": "Explorar reuniones",
            },
            {
                "id": "public_offices",
                "title": "Cargos públicos",
                "description": "Revisa nombramientos, roles y periodos publicados.",
                "examples": [
                    "Cargo A",
                    "Cargo B",
                    "Nombramiento ejemplo",
                ],
                "suggested_sources": ["Diario Oficial", "Transparencia Activa", "SERVEL"],
                "search_query": "cargo publico",
                "cta": "Explorar cargos",
            },
        ],
    }
