from __future__ import annotations


style = {
    "body": {
        "background": "#0f0f12",
        "color": "#f4f4f5",
        "font_family": "IBM Plex Sans, Inter, Segoe UI, sans-serif",
    },
    ".shell": {"min_height": "100vh", "padding": "0 0 28px"},
    ".shell.theme-dark": {"background": "#0f0f12", "color": "#f4f4f5"},
    ".shell.theme-light": {"background": "#f4f4f5", "color": "#18181b"},
    ".shell-main": {"margin_left": "236px", "transition": "margin-left 220ms ease"},
    ".shell.sidebar-collapsed .shell-main": {"margin_left": "72px"},
    ".app-sidebar": {
        "position": "fixed",
        "top": "0",
        "left": "0",
        "bottom": "0",
        "width": "236px",
        "padding": "14px 10px",
        "border_right": "1px solid rgba(161, 161, 170, 0.16)",
        "background": "rgba(15, 15, 18, 0.96)",
        "backdrop_filter": "blur(18px)",
        "z_index": "45",
        "display": "grid",
        "grid_template_rows": "auto",
        "gap": "14px",
        "transition": "width 220ms ease",
    },
    ".shell.theme-light .app-sidebar": {"background": "rgba(255, 255, 255, 0.96)", "border_right": "1px solid rgba(113, 113, 122, 0.18)"},
    ".app-sidebar-collapsed": {"width": "72px"},
    ".sidebar-menu-button": {
        "width": "38px",
        "height": "38px",
        "padding": "0",
        "border_radius": "8px",
        "border": "1px solid rgba(161, 161, 170, 0.2)",
        "background": "rgba(255, 255, 255, 0.06)",
        "justify_self": "center",
        "margin_bottom": "6px",
    },    ".hamburger-icon": {"gap": "4px"},
    ".hamburger-line": {"width": "18px", "height": "2px", "border_radius": "999px", "background": "#e4e4e7"},
    ".shell.theme-light .hamburger-line": {"background": "#18181b"},
    ".sidebar-collapse-button, .sidebar-toggle": {
        "border_radius": "6px",
        "border": "1px solid rgba(161, 161, 170, 0.2)",
        "background": "rgba(255, 255, 255, 0.06)",
        "color": "#e4e4e7",
        "font_weight": "850",
        "min_width": "36px",
    },
    ".shell.theme-light .sidebar-collapse-button, .shell.theme-light .sidebar-toggle, .shell.theme-light .sidebar-menu-button": {"background": "#ffffff", "color": "#18181b"},
    ".sidebar-nav": {"overflow_y": "auto", "padding_right": "2px"},
    ".sidebar-group-label": {"padding": "8px 10px 4px", "color": "#71717a", "font_size": "11px", "font_weight": "850", "letter_spacing": "0.08em", "text_transform": "uppercase"},
    ".sidebar-divider": {"height": "1px", "margin": "10px 8px", "background": "rgba(161, 161, 170, 0.16)"},
    ".sidebar-nav-link": {
        "display": "grid",
        "grid_template_columns": "28px minmax(0, 1fr)",
        "align_items": "center",
        "gap": "8px",
        "padding": "9px 10px",
        "border_radius": "8px",
        "color": "#d4d4d8",
        "font_weight": "750",
        "font_size": "13px",
    },
    ".sidebar-nav-link-active": {"background": "rgba(45, 212, 191, 0.12)", "color": "#ccfbf1"},
    ".shell.theme-light .sidebar-nav-link": {"color": "#3f3f46"},
    ".shell.theme-light .sidebar-nav-link-active": {"background": "rgba(13, 148, 136, 0.12)", "color": "#0f766e"},
    ".sidebar-initial": {"display": "inline-flex", "align_items": "center", "justify_content": "center", "width": "26px", "height": "26px", "border_radius": "6px", "background": "rgba(255, 255, 255, 0.06)", "font_weight": "900"},
    ".sidebar-advanced-toggle": {
        "display": "flex",
        "align_items": "center",
        "justify_content": "space-between",
        "gap": "8px",
        "padding": "9px 10px",
        "border_radius": "8px",
        "border": "1px solid transparent",
        "background": "transparent",
        "color": "#a1a1aa",
        "font_weight": "800",
    },
    ".sidebar-advanced-symbol": {"font_weight": "900", "color": "#ccfbf1"},
    ".sidebar-secondary-nav": {"padding_left": "8px", "border_left": "1px solid rgba(161, 161, 170, 0.16)", "margin_left": "14px"},
    ".app-sidebar-collapsed .sidebar-label, .app-sidebar-collapsed .sidebar-group-label, .app-sidebar-collapsed .sidebar-advanced-symbol, .app-sidebar-collapsed .sidebar-divider": {"display": "none"},
    ".app-sidebar-collapsed .sidebar-nav-link": {"grid_template_columns": "1fr", "justify_items": "center", "padding": "9px 6px"},
    ".app-sidebar-collapsed .sidebar-advanced-toggle": {"justify_content": "center", "padding": "9px 6px"},
    ".shell-header": {
        "width": "100%",
        "border_bottom": "1px solid rgba(161, 161, 170, 0.10)",
        "background": "rgba(15, 15, 18, 0.72)",
        "backdrop_filter": "blur(18px)",
    },
    ".shell.theme-light .shell-header": {
        "background": "rgba(255, 255, 255, 0.88)",
        "border_bottom": "1px solid rgba(113, 113, 122, 0.18)",
    },
    ".nav-inner": {
        "max_width": "1760px",
        "margin": "0 auto",
        "width": "min(calc(100% - 48px), 1760px)",
        "padding": "10px 0",
        "gap": "16px",
    },
    ".page": {"max_width": "1760px", "margin": "0 auto", "width": "min(calc(100% - 48px), 1760px)"},
    ".site-footer": {
        "width": "min(calc(100% - 48px), 1760px)",
        "max_width": "1760px",
        "margin": "28px auto 0",
        "padding": "26px 0 0",
        "border_top": "1px solid rgba(161, 161, 170, 0.18)",
        "display": "grid",
        "gap": "18px",
    },
    ".footer-grid": {"max_width": "900px", "width": "100%", "margin": "0 auto", "align_items": "start"},
    ".footer-column": {"display": "grid", "gap": "8px", "align_content": "start"},
    ".footer-column-title": {"font_size": "11px", "font_weight": "850", "letter_spacing": "0.08em", "text_transform": "uppercase", "color": "#a1a1aa"},
    ".footer-copy": {"font_size": "13px", "color": "#a1a1aa"},
    ".footer-column-copy": {"margin_bottom": "2px"},
    ".footer-bottom-copy": {"text_align": "center"},
    ".footer-link": {"font_size": "13px", "color": "#d4d4d8", "font_weight": "600"},
    ".footer-column-link": {"width": "fit-content"},
    ".footer-link-icon": {"font_size": "13px", "width": "18px", "color": "#a1a1aa"},
    ".footer-link-label": {"font_size": "13px"},
    ".support-inline-block": {"display": "grid", "gap": "8px", "padding": "14px", "border": "1px solid rgba(45, 212, 191, 0.16)", "border_radius": "8px", "background": "rgba(45, 212, 191, 0.06)", "max_width": "520px"},
    ".support-copy": {"font_size": "14px", "line_height": "1.45", "color": "#d4d4d8"},
    ".support-mini-button": {"width": "fit-content"},
    ".support-action-card": {"display": "grid", "gap": "10px", "align_content": "start"},
    ".support-action-link": {"width": "fit-content"},
    ".shell.theme-light .footer-copy": {"color": "#71717a"},
    ".shell.theme-light .footer-link": {"color": "#374151"},
    ".shell.theme-light .support-copy": {"color": "#374151"},
    ".brand": {"font_size": "20px", "font_weight": "800", "letter_spacing": "0.02em", "color": "#f4f4f5"},
    ".shell.theme-light .brand": {"color": "#18181b"},
    ".nav-links": {"flex_wrap": "wrap", "gap": "22px", "justify_content": "center"},
    ".nav-link": {
        "display": "inline-flex",
        "align_items": "center",
        "justify_content": "center",
        "padding": "8px 2px 10px",
        "border_bottom": "2px solid transparent",
        "background": "transparent",
        "color": "#d4d4d8",
        "font_weight": "600",
    },
    ".nav-link-active": {
        "border_bottom": "2px solid #2dd4bf",
        "color": "#f4f4f5",
    },
    ".shell.theme-light .nav-link": {
        "background": "transparent",
        "color": "#18181b",
    },
    ".shell.theme-light .nav-link-active": {
        "border_bottom": "2px solid #c084fc",
        "color": "#18181b",
    },
    ".header-search": {"position": "relative", "flex_wrap": "wrap", "justify_content": "flex-end"},
    ".header-search-toggle": {
        "border_radius": "999px",
        "padding": "8px 14px",
        "border": "1px solid rgba(45, 212, 191, 0.28)",
        "background": "rgba(45, 212, 191, 0.12)",
        "color": "#ccfbf1",
        "font_weight": "700",
    },
    ".header-search-popover": {
        "padding": "6px",
        "border": "1px solid rgba(161, 161, 170, 0.22)",
        "border_radius": "8px",
        "background": "rgba(24, 24, 27, 0.96)",
    },
    ".header-search-input": {"width": "220px", "min_height": "36px", "font_size": "14px"},
    ".header-search-submit": {
        "border_radius": "6px",
        "padding": "8px 12px",
        "background": "#2dd4bf",
        "color": "#042f2e",
        "font_weight": "800",
    },
    ".shell.theme-light .header-search-toggle": {
        "background": "rgba(13, 148, 136, 0.12)",
        "color": "#0f766e",
    },
    ".shell.theme-light .header-search-popover": {
        "background": "rgba(255, 255, 255, 0.98)",
        "border": "1px solid rgba(113, 113, 122, 0.24)",
    },
    ".theme-toggle": {
        "border_radius": "999px",
        "padding": "8px 14px",
        "border": "1px solid rgba(167, 139, 250, 0.25)",
        "background": "rgba(167, 139, 250, 0.16)",
        "color": "#f4f4f5",
        "font_weight": "700",
    },
    ".shell.theme-light .theme-toggle": {
        "background": "rgba(167, 139, 250, 0.12)",
        "color": "#18181b",
    },
    ".shell-alert": {
        "width": "min(calc(100% - 48px), 1760px)",
        "max_width": "1760px",
        "margin": "16px auto 0",
        "display": "grid",
        "gap": "10px",
        "border_left": "3px solid rgba(250, 204, 21, 0.58)",
    },
    ".shell-alert-actions": {"gap": "10px"},
    "a:focus-visible, button:focus-visible, input:focus-visible, textarea:focus-visible, select:focus-visible, iframe:focus-visible": {
        "outline": "3px solid rgba(45, 212, 191, 0.72)",
        "outline_offset": "3px",
    },
    ".hero": {
        "border": "1px solid rgba(161, 161, 170, 0.10)",
        "border_radius": "10px",
        "padding": "28px",
        "background": "rgba(24, 24, 27, 0.72)",
    },
    ".page-home .hero": {
        "padding": "54px 0 34px",
        "border": "0",
        "border_radius": "0",
        "background": "transparent",
        "max_width": "960px",
    },
    ".page-investigation .hero": {"border_left": "4px solid rgba(45, 212, 191, 0.55)"},
    ".page-library .hero": {"border_left": "4px solid rgba(167, 139, 250, 0.58)"},
    ".page-document .hero": {"border_left": "4px solid rgba(228, 228, 231, 0.58)"},
    ".page-tracking .hero": {"border_left": "4px solid rgba(74, 222, 128, 0.56)"},
    ".page-reports .hero": {"border_left": "4px solid rgba(251, 146, 60, 0.58)"},
    ".page-ecosystem .hero": {"border_left": "4px solid rgba(96, 165, 250, 0.58)"},
    ".page-project .hero": {"border_left": "4px solid rgba(161, 161, 170, 0.62)"},
    ".page-home .title": {"color": "#f4f4f5"},
    ".page-investigation .title": {"color": "#ccfbf1"},
    ".page-library .title": {"color": "#ddd6fe"},
    ".page-document .title": {"color": "#f4f4f5"},
    ".page-tracking .title": {"color": "#bbf7d0"},
    ".page-reports .title": {"color": "#fed7aa"},
    ".page-ecosystem .title": {"color": "#bfdbfe"},
    ".page-project .title": {"color": "#e4e4e7"},
    ".shell.theme-light .hero": {
        "background": "linear-gradient(180deg, rgba(255, 255, 255, 0.98), rgba(247, 247, 248, 0.98))",
        "border_color": "rgba(113, 113, 122, 0.18)",
    },
    ".title": {"font_size": "42px", "font_weight": "850", "line_height": "1.08"},
    ".subtitle": {"color": "#a1a1aa", "max_width": "820px", "line_height": "1.55"},
    ".shell.theme-light .subtitle": {"color": "#71717a"},
    ".section-title": {"font_size": "20px", "font_weight": "700", "margin_bottom": "12px", "color": "#f4f4f5"},
    ".page-reports .section-title": {"font_size": "24px", "font_weight": "800", "color": "#fed7aa"},
    ".page-library .section-title": {"color": "#ddd6fe"},
    ".page-document .section-title": {"color": "#f4f4f5"},
    ".page-tracking .section-title": {"color": "#bbf7d0"},
    ".page-investigation .section-title": {"color": "#ccfbf1"},
    ".page-ecosystem .section-title": {"color": "#bfdbfe"},
    ".page-project .section-title": {"color": "#e4e4e7"},
    ".shell.theme-light .section-title": {"color": "#18181b"},
    ".section-subtitle": {"color": "#a1a1aa", "margin_bottom": "14px"},
    ".shell.theme-light .section-subtitle": {"color": "#71717a"},
    ".page-section": {
        "display": "grid",
        "gap": "14px",
        "padding": "10px 0 22px",
    },
    ".page-home .page-section": {"padding": "12px 0 18px"},
    ".page-reports .page-section": {
        "width": "100%",
        "max_width": "1180px",
        "margin": "0 auto",
        "padding": "24px 0",
        "border_top": "1px solid rgba(251, 146, 60, 0.16)",
    },
    ".page-reports .reports-article-section": {"max_width": "980px"},
    ".page-reports .reports-catalog-section, .page-reports .reports-wide-section": {"max_width": "1180px"},
    ".page-library .page-section": {
        "padding": "22px 0",
        "border_top": "1px solid rgba(167, 139, 250, 0.14)",
    },
    ".page-document .page-section": {
        "padding": "18px 0",
        "border_top": "1px solid rgba(228, 228, 231, 0.12)",
    },
    ".page-tracking .page-section": {
        "padding": "20px 0",
        "border_top": "1px solid rgba(74, 222, 128, 0.14)",
    },
    ".page-ecosystem .page-section": {
        "padding": "20px 0",
        "border_top": "1px solid rgba(96, 165, 250, 0.14)",
    },
    ".page-project .page-section": {
        "padding": "20px 0",
        "border_top": "1px solid rgba(161, 161, 170, 0.14)",
    },
    ".current-topic-card": {
        "border": "1px solid rgba(161, 161, 170, 0.10)",
        "border_radius": "8px",
        "padding": "16px",
        "background": "#18181b",
        "display": "grid",
        "gap": "10px",
        "align_content": "start",
    },
    ".shell.theme-light .current-topic-card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".topic-answer-card": {
        "border": "1px solid rgba(161, 161, 170, 0.10)",
        "border_radius": "8px",
        "padding": "14px",
        "background": "#18181b",
        "display": "grid",
        "gap": "8px",
        "align_content": "start",
    },
    ".topic-status-card": {"min_height": "110px", "align_content": "start"},
    ".topic-card-document": {"border_left": "3px solid rgba(45, 212, 191, 0.62)"},
    ".topic-card-proposes": {"border_left": "3px solid rgba(96, 165, 250, 0.62)"},
    ".topic-card-changes": {"border_left": "3px solid rgba(167, 139, 250, 0.62)"},
    ".topic-card-no-change": {"border_left": "3px solid rgba(250, 204, 21, 0.62)"},
    ".topic-card-next": {"border_left": "3px solid rgba(74, 222, 128, 0.62)"},
    ".topic-card-evidence": {"border_left": "3px solid rgba(251, 146, 60, 0.62)"},
    ".topic-card-evidence-active": {"border_color": "rgba(251, 146, 60, 0.64)", "background": "rgba(251, 146, 60, 0.10)", "box_shadow": "0 0 0 3px rgba(251, 146, 60, 0.10)"},
    ".page-topic .shell-header": {"position": "sticky", "top": "0", "z_index": "20"},
    ".page-topic .nav-inner": {"padding": "8px 0", "gap": "10px"},
    ".page-topic .nav-links": {"gap": "12px", "font_size": "13px"},
    ".page-topic .header-search-toggle, .page-topic .theme-toggle": {"padding": "6px 10px"},
    ".sidebar-ready-nav": {"min_width": "0"},
    ".top-minimal-nav": {"flex": "0 1 auto"},
    ".scroll-top-button": {
        "position": "fixed",
        "right": "24px",
        "bottom": "24px",
        "z_index": "60",
        "opacity": "0",
        "pointer_events": "none",
        "transform": "translateY(14px)",
        "transition": "opacity 180ms ease, transform 180ms ease",
        "border_radius": "999px",
        "border": "1px solid rgba(45, 212, 191, 0.34)",
        "background": "rgba(15, 118, 110, 0.92)",
        "color": "#ecfeff",
        "font_weight": "850",
        "box_shadow": "0 14px 40px rgba(0, 0, 0, 0.22)",
    },
    ".scroll-top-button.scroll-top-visible": {"opacity": "1", "pointer_events": "auto", "transform": "translateY(0)"},
    ".home-pulse-hero": {"padding_bottom": "34px"},
    ".hero-action-note": {"color": "#a1a1aa", "font_size": "14px", "align_self": "center"},
    ".primary-action": {"padding": "13px 18px", "border_radius": "8px"},
    ".topic-mode-selector": {
        "padding": "6px",
        "border": "1px solid rgba(161, 161, 170, 0.10)",
        "border_radius": "8px",
        "background": "rgba(255, 255, 255, 0.04)",
        "width": "fit-content",
    },
    ".topic-mode-button": {
        "border_radius": "6px",
        "border": "1px solid transparent",
        "background": "transparent",
        "color": "#d4d4d8",
        "font_weight": "800",
    },
    ".topic-mode-button-active": {"background": "rgba(45, 212, 191, 0.14)", "border_color": "rgba(45, 212, 191, 0.28)", "color": "#ccfbf1"},
    ".shell.theme-light .topic-mode-selector": {"background": "rgba(255, 255, 255, 0.72)", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".shell.theme-light .topic-mode-button": {"color": "#3f3f46"},
    ".shell.theme-light .topic-mode-button-active": {"background": "rgba(13, 148, 136, 0.12)", "border_color": "rgba(13, 148, 136, 0.24)", "color": "#0f766e"},
    ".topic-mode-shell": {"min_width": "0"},
    ".topic-single-mode": {"display": "grid", "gap": "14px", "max_width": "980px", "width": "100%", "margin": "0 auto", "padding": "0 0 22px"},
    ".topic-single-mode .topic-source-panel": {"position": "relative", "top": "auto", "max_height": "80vh"},
    ".topic-system-placeholder": {
        "display": "grid",
        "gap": "16px",
        "padding": "18px",
        "border": "1px solid rgba(74, 222, 128, 0.22)",
        "border_radius": "8px",
        "background": "#18181b",
    },
    ".topic-evidence-mode-panel": {"align_self": "start"},
    ".pulse-field": {"display": "grid", "gap": "4px", "padding_top": "8px", "border_top": "1px solid rgba(161, 161, 170, 0.12)"},
    ".pulse-field-label": {"font_size": "11px", "font_weight": "850", "letter_spacing": "0.07em", "text_transform": "uppercase", "color": "#a1a1aa"},
    ".document-sheet": {
        "border": "1px solid rgba(113, 113, 122, 0.18)",
        "border_radius": "8px",
        "padding": "38px",
        "background": "#f8fafc",
        "color": "#18181b",
        "box_shadow": "0 18px 60px rgba(0, 0, 0, 0.18)",
    },
    ".document-sheet-cover": {"display": "grid", "gap": "6px", "padding_bottom": "18px", "border_bottom": "1px solid rgba(113, 113, 122, 0.18)", "margin_bottom": "6px"},
    ".document-sheet-title": {"font_size": "20px", "font_weight": "850", "line_height": "1.25", "color": "#111827"},
    ".live-system-heading": {"display": "grid", "gap": "6px"},
    ".live-stage-grid": {"align_items": "stretch"},
    ".live-stage-card": {
        "min_height": "118px",
        "padding": "14px",
        "border": "1px solid rgba(45, 212, 191, 0.18)",
        "border_radius": "8px",
        "background": "rgba(255, 255, 255, 0.04)",
        "display": "grid",
        "gap": "7px",
        "align_content": "start",
    },
    ".live-stage-state": {"font_size": "12px", "font_weight": "850", "color": "#ccfbf1"},
    ".live-stage-title": {"font_size": "16px", "font_weight": "850", "color": "#f4f4f5"},
    ".live-stage-body": {"font_size": "13px", "line_height": "1.45", "color": "#a1a1aa"},
    ".live-timeline-panel": {"overflow": "hidden"},
    ".live-timeline-strip": {"overflow_x": "auto", "padding_bottom": "8px", "scroll_snap_type": "x proximity"},
    ".live-timeline-strip .tracking-event-card": {"flex": "0 0 270px", "scroll_snap_align": "start"},
    ".topic-document-first-layout": {
        "display": "grid",
        "grid_template_columns": "minmax(0, 58fr) minmax(64px, 0.08fr) minmax(0, 42fr)",
        "gap": "14px",
        "align_items": "start",
        "width": "100%",
        "padding": "0 0 22px",
    },
    ".topic-source-panel": {
        "position": "sticky",
        "top": "72px",
        "max_height": "86vh",
        "overflow_y": "auto",
        "border": "1px solid rgba(45, 212, 191, 0.18)",
        "border_radius": "8px",
        "padding": "14px",
        "background": "#18181b",
        "display": "grid",
        "gap": "12px",
        "align_content": "start",
    },
    ".shell.theme-light .topic-source-panel": {"background": "#ffffff", "color": "#18181b"},
    ".topic-source-header": {"align_items": "center"},
    ".topic-current-anchor": {"position": "sticky", "top": "0", "z_index": "3"},
    ".topic-source-guidance": {"font_size": "13px", "line_height": "1.45", "color": "#a1a1aa", "border_left": "3px solid rgba(45, 212, 191, 0.34)", "padding_left": "10px"},
    ".shell.theme-light .topic-source-guidance": {"color": "#52525b"},
    ".topic-source-excerpt": {"color": "#27272a", "font_size": "14px", "line_height": "1.55"},
    ".topic-document-page": {"gap": "12px"},
    ".topic-original-link": {"width": "fit-content"},
    ".topic-pdf-document-viewer": {"display": "grid", "gap": "12px"},
    ".topic-pdf-frame": {"width": "100%", "min_height": "68vh", "border": "1px solid rgba(113, 113, 122, 0.18)", "border_radius": "8px", "background": "#f8fafc"},
    ".topic-pdf-citation-panel": {"border_left": "4px solid #0f766e", "padding": "10px 12px", "background": "rgba(13, 148, 136, 0.08)", "display": "grid", "gap": "6px"},
    ".topic-context-rail": {"position": "sticky", "top": "72px", "max_height": "86vh", "display": "grid", "gap": "7px", "align_content": "start", "padding": "8px 6px", "border_left": "1px solid rgba(161, 161, 170, 0.16)", "border_right": "1px solid rgba(161, 161, 170, 0.10)"},
    ".topic-rail-label": {"font_size": "11px", "font_weight": "850", "text_transform": "uppercase", "letter_spacing": "0.04em", "color": "#a1a1aa"},
    ".topic-rail-link": {"font_size": "12px", "line_height": "1.25", "color": "#ccfbf1", "border_radius": "6px", "padding": "5px 6px", "background": "rgba(45, 212, 191, 0.07)"},
    ".shell.theme-light .topic-rail-link": {"color": "#0f766e", "background": "rgba(45, 212, 191, 0.08)"},
    ".topic-reading-column": {"min_width": "0", "display": "grid", "gap": "16px"},
    ".topic-reading-flow": {"width": "100%"},
    ".topic-reading-section": {
        "border": "1px solid rgba(161, 161, 170, 0.10)",
        "border_radius": "8px",
        "padding": "16px",
        "background": "#18181b",
        "display": "grid",
        "gap": "14px",
        "scroll_margin_top": "82px",
    },
    ".shell.theme-light .topic-reading-section": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".topic-compact-grid": {"width": "100%"},
    ".topic-evidence-grid": {"align_items": "stretch"},
    ".shell.theme-light .topic-answer-card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".card": {
        "border": "1px solid rgba(161, 161, 170, 0.10)",
        "border_radius": "16px",
        "padding": "16px",
        "background": "#18181b",
    },
    ".shell.theme-light .card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)", "color": "#18181b"},
    ".error": {"border_color": "rgba(248, 113, 113, 0.55)"},
    ".metric-card": {
        "min_width": "160px",
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "16px",
        "padding": "14px",
        "background": "#1f1f24",
    },
    ".shell.theme-light .metric-card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".metric-value": {"font_size": "26px", "font_weight": "800", "color": "#2dd4bf"},
    ".summary-card": {
        "min_width": "150px",
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "16px",
        "padding": "12px",
        "background": "#1f1f24",
        "display": "grid",
        "gap": "4px",
    },
    ".shell.theme-light .summary-card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".summary-label": {"font_size": "12px", "color": "#a1a1aa", "text_transform": "uppercase", "letter_spacing": "0.04em"},
    ".shell.theme-light .summary-label": {"color": "#71717a"},
    ".summary-value": {"font_size": "22px", "font_weight": "800", "color": "#2dd4bf"},
    ".card-title": {"font_weight": "800", "font_size": "18px"},
    ".muted": {"color": "#a1a1aa"},
    ".shell.theme-light .muted": {"color": "#71717a"},
    ".small": {"font_size": "13px"},
    ".badge": {
        "display": "inline-flex",
        "border_radius": "999px",
        "padding": "4px 9px",
        "border": "1px solid rgba(45, 212, 191, 0.22)",
        "background": "rgba(45, 212, 191, 0.12)",
        "color": "#2dd4bf",
        "font_size": "13px",
        "font_weight": "700",
    },
    ".badge-teal": {"background": "rgba(45, 212, 191, 0.14)", "color": "#2dd4bf", "border_color": "rgba(45, 212, 191, 0.3)"},
    ".badge-purple": {"background": "rgba(167, 139, 250, 0.14)", "color": "#a78bfa", "border_color": "rgba(167, 139, 250, 0.3)"},
    ".launch-notice": {"width": "fit-content", "margin_top": "6px"},
    ".badge-amber": {"background": "rgba(250, 204, 21, 0.14)", "color": "#facc15", "border_color": "rgba(250, 204, 21, 0.28)"},
    ".page-tracking .badge-teal": {"background": "rgba(74, 222, 128, 0.12)", "color": "#86efac", "border_color": "rgba(74, 222, 128, 0.28)"},
    ".page-reports .badge-teal": {"background": "rgba(251, 146, 60, 0.12)", "color": "#fdba74", "border_color": "rgba(251, 146, 60, 0.28)"},
    ".page-ecosystem .badge-teal": {"background": "rgba(96, 165, 250, 0.12)", "color": "#93c5fd", "border_color": "rgba(96, 165, 250, 0.28)"},
    ".mini-pill": {
        "border": "1px solid rgba(45, 212, 191, 0.22)",
        "border_radius": "999px",
        "padding": "3px 8px",
        "background": "rgba(45, 212, 191, 0.1)",
        "color": "#d4d4d8",
        "font_size": "12px",
    },
    ".mini-pill-purple": {"background": "rgba(167, 139, 250, 0.12)", "border_color": "rgba(167, 139, 250, 0.24)", "color": "#e4e4e7"},
    ".story-chip": {
        "border": "1px solid rgba(167, 139, 250, 0.24)",
        "border_radius": "999px",
        "padding": "3px 8px",
        "background": "rgba(167, 139, 250, 0.12)",
        "color": "#e4e4e7",
        "font_size": "12px",
    },
    ".prompt-chip": {
        "border": "1px solid rgba(45, 212, 191, 0.22)",
        "border_radius": "999px",
        "padding": "3px 8px",
        "background": "rgba(45, 212, 191, 0.1)",
        "color": "#e4e4e7",
        "font_size": "12px",
    },
    ".comparison-chip": {
        "border": "1px solid rgba(45, 212, 191, 0.22)",
        "border_radius": "999px",
        "padding": "3px 8px",
        "background": "rgba(45, 212, 191, 0.1)",
        "color": "#d4d4d8",
        "font_size": "12px",
    },
    ".evidence-trust": {"background": "rgba(250, 204, 21, 0.1)", "border_color": "rgba(250, 204, 21, 0.22)"},
    ".canonical-link-box": {
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "8px",
        "padding": "10px",
        "background": "#1f1f24",
        "overflow_wrap": "anywhere",
    },
    ".topic-card": {"min_height": "130px", "display": "grid", "gap": "8px", "align_content": "start"},
    ".topic-grid": {"align_items": "stretch"},
    ".source-coverage-card": {"max_width": "none", "width": "100%"},
    ".search-chip": {
        "border": "1px solid rgba(113, 113, 122, 0.2)",
        "border_radius": "999px",
        "padding": "8px 12px",
        "background": "#1f1f24",
        "color": "#f4f4f5",
    },
    ".search-chip-text": {"font_size": "13px", "font_weight": "600"},
    ".flow-card": {
        "display": "grid",
        "gap": "8px",
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "background": "#1f1f24",
    },
    ".flow-accent": {"font_size": "12px", "font_weight": "800", "letter_spacing": "0.08em"},
    ".flow-accent-teal": {"color": "#2dd4bf"},
    ".flow-accent-purple": {"color": "#a78bfa"},
    ".flow-accent-amber": {"color": "#facc15"},
    ".example-card": {"display": "grid", "gap": "8px"},
    ".prompt-card": {"display": "grid", "gap": "8px"},
    ".button": {
        "background": "#2dd4bf",
        "color": "#0b0b0f",
        "border_radius": "12px",
        "font_weight": "700",
    },
    ".button-secondary": {
        "background": "rgba(167, 139, 250, 0.14)",
        "color": "#f4f4f5",
        "border": "1px solid rgba(167, 139, 250, 0.28)",
    },
    ".shell.theme-light .button": {"color": "#18181b"},
    ".shell.theme-light .button-secondary": {"color": "#18181b"},
    ".input": {
        "background": "#18181b",
        "border": "1px solid rgba(161, 161, 170, 0.22)",
        "color": "#f4f4f5",
    },
    ".shell.theme-light .input": {
        "background": "#ffffff",
        "border_color": "rgba(113, 113, 122, 0.24)",
        "color": "#18181b",
    },
    ".search-bar": {"width": "100%", "align_items": "center"},
    ".search-input": {"min_width": "520px", "width": "100%", "font_size": "16px", "padding": "14px 16px"},
    ".search-button": {"padding": "12px 18px"},
    ".hero-actions": {"margin_top": "18px"},
    ".investigation-layout": {
        "display": "grid",
        "grid_template_columns": "minmax(0, 0.95fr) minmax(0, 1.35fr) minmax(280px, 0.8fr)",
        "gap": "16px",
        "align_items": "start",
        "width": "100%",
        "overflow": "visible",
    },
    ".investigation-shell": {"display": "grid", "gap": "14px", "width": "min(95vw, 1600px)", "margin": "0 auto"},
    ".product-investigation-flow": {
        "display": "grid",
        "gap": "18px",
        "width": "100%",
        "max_width": "1600px",
        "margin": "0 auto",
    },
    ".product-metric-card": {
        "min_width": "190px",
        "flex": "1 1 190px",
    },
    ".story-main": {"min_width": "0"},
    ".investigation-left": {"display": "grid", "gap": "12px", "min_width": "0"},
    ".investigation-center": {"display": "grid", "gap": "12px", "min_width": "0"},
    ".investigation-sidebar": {"max_height": "none", "overflow_y": "visible", "min_width": "0"},
    ".context-panel": {"position": "static", "top": "auto", "display": "grid", "gap": "12px", "min_width": "0", "align_self": "start"},
    ".investigation-card": {"padding": "12px", "gap": "8px"},
    ".investigation-section-title": {"margin_bottom": "4px", "font_size": "18px"},
    ".investigation-subtitle": {"margin_bottom": "4px", "font_size": "13px"},
    ".timeline-accordion": {"margin_top": "6px"},
    ".story-card": {
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "14px",
        "padding": "10px",
        "background": "#1f1f24",
        "display": "grid",
        "gap": "6px",
    },
    ".shell.theme-light .story-card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".story-title": {"font_size": "15px", "font_weight": "800"},
    ".story-headline": {"font_size": "22px", "font_weight": "800"},
    ".story-summary": {"color": "#e4e4e7", "line_height": "1.55"},
    ".story-summary-dominant": {"font_size": "15px"},
    ".narrative-item": {
        "border": "1px solid rgba(161, 161, 170, 0.12)",
        "border_radius": "14px",
        "padding": "8px",
        "background": "#1f1f24",
    },
    ".document-hero": {
        "padding": "20px 0 10px",
        "display": "grid",
        "gap": "14px",
        "border_bottom": "1px solid rgba(228, 228, 231, 0.12)",
    },
    ".document-hero-copy": {"display": "grid", "gap": "8px", "max_width": "1040px"},
    ".document-kicker": {"font_size": "13px", "font_weight": "800", "letter_spacing": "0.08em", "text_transform": "uppercase", "color": "#2dd4bf"},
    ".document-title": {"font_size": "34px", "font_weight": "850", "line_height": "1.12", "color": "#f4f4f5", "max_width": "1080px"},
    ".document-subtitle": {"font_size": "16px", "line_height": "1.55", "color": "#a1a1aa", "max_width": "860px"},
    ".document-meta-row": {"align_items": "center"},
    ".document-meta-pill": {
        "border": "1px solid rgba(161, 161, 170, 0.22)",
        "border_radius": "999px",
        "padding": "5px 10px",
        "font_size": "12px",
        "color": "#d4d4d8",
        "background": "rgba(24, 24, 27, 0.72)",
    },
    ".document-meta-reference": {"font_family": "Consolas, monospace", "font_size": "12px", "color": "#a1a1aa", "overflow_wrap": "anywhere"},
    ".official-document-layout": {
        "display": "grid",
        "grid_template_columns": "minmax(0, 1.95fr) minmax(340px, 0.72fr)",
        "gap": "28px",
        "align_items": "start",
        "padding": "22px 0",
    },
    ".document-main-column": {"min_width": "0"},
    ".document-side-column": {"min_width": "0", "position": "sticky", "top": "88px"},
    ".official-document-viewer": {"display": "grid", "gap": "14px"},
    ".reading-context-bar": {
        "border": "1px solid rgba(161, 161, 170, 0.10)",
        "border_radius": "8px",
        "padding": "12px",
        "background": "#18181b",
        "display": "grid",
        "grid_template_columns": "minmax(190px, 1fr) repeat(4, minmax(110px, auto))",
        "gap": "10px",
        "align_items": "center",
    },
    ".document-reading-status": {"font_weight": "800", "color": "#ccfbf1"},
    ".document-metric": {"display": "grid", "gap": "2px"},
    ".document-metric-value": {"font_size": "20px", "font_weight": "850", "color": "#f4f4f5"},
    ".document-metric-label": {"font_size": "11px", "color": "#a1a1aa", "text_transform": "uppercase", "letter_spacing": "0.04em"},
    ".document-paper": {
        "border": "1px solid rgba(228, 228, 231, 0.16)",
        "border_radius": "8px",
        "padding": "28px",
        "background": "#f8fafc",
        "color": "#18181b",
        "display": "grid",
        "gap": "18px",
        "box_shadow": "0 18px 60px rgba(0, 0, 0, 0.18)",
    },
    ".document-label": {"font_size": "12px", "font_weight": "850", "letter_spacing": "0.08em", "text_transform": "uppercase", "color": "#0f766e"},
    ".document-page-nav": {"border_bottom": "1px solid rgba(113, 113, 122, 0.18)", "padding_bottom": "12px"},
    ".page-chip": {
        "border": "1px solid rgba(113, 113, 122, 0.22)",
        "border_radius": "6px",
        "background": "#ffffff",
        "color": "#18181b",
        "font_weight": "800",
    },
    ".page-chip-active": {"border_color": "#0f766e", "background": "rgba(13, 148, 136, 0.1)", "color": "#0f766e"},
    ".document-current-anchor": {
        "border_left": "4px solid #0f766e",
        "padding": "10px 12px",
        "background": "rgba(13, 148, 136, 0.08)",
        "display": "grid",
        "gap": "6px",
    },
    ".document-page-label": {"font_weight": "850", "color": "#18181b"},
    ".document-highlight": {"color": "#374151", "line_height": "1.55"},
    ".document-location-notice": {"font_size": "12px", "line_height": "1.4", "color": "#92400e", "background": "rgba(251, 191, 36, 0.16)", "border": "1px solid rgba(251, 191, 36, 0.28)", "border_radius": "6px", "padding": "7px 9px"},
    ".document-page": {"display": "grid", "gap": "18px", "scroll_behavior": "smooth"},
    ".document-fragment": {
        "border": "1px solid transparent",
        "border_radius": "4px",
        "padding": "12px 4px 14px",
        "background": "transparent",
        "display": "grid",
        "gap": "8px",
        "cursor": "pointer",
        "scroll_margin_top": "28px",
    },
    ".document-fragment + .document-fragment": {"border_top": "1px solid rgba(113, 113, 122, 0.13)"},
    ".document-fragment-active": {"border_color": "rgba(13, 148, 136, 0.55)", "background": "rgba(204, 251, 241, 0.72)", "box_shadow": "0 0 0 3px rgba(13, 148, 136, 0.13)", "animation": "document-pulse 2.8s ease-out"},
    ".document-page-marker": {"font_size": "11px", "font_weight": "850", "color": "#0f766e", "letter_spacing": "0.05em", "text_transform": "uppercase"},
    ".document-section-title": {"font_size": "13px", "font_weight": "850", "color": "#374151"},
    ".document-fragment-text": {"font_size": "17px", "line_height": "1.85", "color": "#18181b"},
    ".fragment-supports": {"border_top": "1px solid rgba(113, 113, 122, 0.14)", "padding_top": "10px", "display": "grid", "gap": "8px"},
    ".document-cross-label": {"font_size": "12px", "font_weight": "800", "color": "#52525b"},
    ".document-inline-link": {
        "border_bottom": "1px solid rgba(13, 148, 136, 0.45)",
        "color": "#0f766e",
        "font_weight": "800",
        "font_size": "13px",
    },
    ".reading-guide-panel": {
        "border_left": "1px solid rgba(161, 161, 170, 0.18)",
        "padding_left": "20px",
        "display": "grid",
        "gap": "16px",
    },
    ".reading-guide-title": {"font_size": "24px", "font_weight": "850", "color": "#f4f4f5"},
    ".reading-guide-summary": {"font_size": "15px", "line_height": "1.55", "color": "#d4d4d8"},
    ".reading-guide-section": {"display": "grid", "gap": "9px", "padding_top": "12px", "border_top": "1px solid rgba(161, 161, 170, 0.14)"},
    ".reading-guide-heading": {"font_size": "12px", "font_weight": "850", "letter_spacing": "0.06em", "text_transform": "uppercase", "color": "#a1a1aa"},
    ".guide-entry": {"display": "grid", "gap": "7px", "padding": "3px 0", "cursor": "pointer"},
    ".guide-title": {"font_size": "15px", "font_weight": "850", "color": "#f4f4f5", "line_height": "1.35"},
    ".guide-copy": {"font_size": "13px", "line_height": "1.5", "color": "#a1a1aa"},
    ".guide-evidence": {"display": "grid", "gap": "6px"},
    ".reference-button": {
        "width": "fit-content",
        "border_radius": "6px",
        "background": "rgba(45, 212, 191, 0.12)",
        "border": "1px solid rgba(45, 212, 191, 0.18)",
        "color": "#ccfbf1",
        "font_weight": "850",
        "font_size": "12px",
    },
    ".document-reference-section": {"padding": "18px 0 8px", "border_top": "1px solid rgba(228, 228, 231, 0.12)", "display": "grid", "gap": "12px"},
    ".reference-strip": {"display": "grid", "grid_template_columns": "repeat(4, minmax(0, 1fr))", "gap": "18px"},
    ".shell.theme-light .document-title, .shell.theme-light .reading-guide-title, .shell.theme-light .guide-title": {"color": "#18181b"},
    ".shell.theme-light .document-subtitle, .shell.theme-light .reading-guide-summary, .shell.theme-light .guide-copy": {"color": "#52525b"},
    ".shell.theme-light .reading-context-bar": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".shell.theme-light .document-reading-status": {"color": "#0f766e"},
    ".shell.theme-light .document-metric-value": {"color": "#18181b"},
    ".shell.theme-light .reading-guide-panel": {"border_left": "1px solid rgba(113, 113, 122, 0.2)"},
    ".knowledge-point": {
        "border": "1px solid rgba(45, 212, 191, 0.16)",
        "border_left": "3px solid rgba(45, 212, 191, 0.42)",
        "border_radius": "8px",
        "padding": "12px",
        "background": "rgba(24, 24, 27, 0.42)",
        "display": "grid",
        "gap": "8px",
    },
    ".shell.theme-light .narrative-item": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.16)"},
    ".narrative-text": {"font_size": "13px", "color": "#e4e4e7", "line_height": "1.45"},
    ".detail-line": {
        "border_top": "1px solid rgba(161, 161, 170, 0.14)",
        "padding_top": "7px",
        "color": "#e4e4e7",
    },
    ".shell.theme-light .detail-line": {"color": "#374151", "border_top": "1px solid rgba(113, 113, 122, 0.18)"},
    ".technical-inline": {"display": "none"},
    ".technical-accordion": {"margin_top": "4px"},
    ".technical-bottom": {
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "16px",
        "padding": "10px 14px",
        "background": "#18181b",
    },
    ".shell.theme-light .technical-bottom": {
        "background": "#ffffff",
        "border_color": "rgba(113, 113, 122, 0.18)",
    },
    ".technical-item": {"padding": "8px"},
    ".fact-line": {"white_space": "pre-wrap", "color": "#e4e4e7", "line_height": "1.4"},
    ".context-title": {"font_weight": "800", "color": "#f4f4f5"},
    ".shell.theme-light .context-title": {"color": "#18181b"},
    ".context-item": {
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "14px",
        "padding": "8px",
        "display": "grid",
        "gap": "4px",
        "background": "#1f1f24",
    },
    ".shell.theme-light .context-item": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".context-block": {"display": "grid", "gap": "8px"},
    ".context-number": {"font_weight": "800", "color": "#2dd4bf"},
    ".mono": {"font_family": "Consolas, monospace", "font_size": "12px", "white_space": "pre-wrap"},
    ".id-line": {"color": "#a1a1aa", "overflow_wrap": "anywhere"},
    ".shell.theme-light .id-line": {"color": "#71717a"},
    ".relationship-map": {
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "14px",
        "padding": "12px",
        "display": "grid",
        "gap": "8px",
        "background": "#1f1f24",
        "overflow_x": "auto",
        "max_width": "100%",
    },
    ".shell.theme-light .relationship-map": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".map-node": {
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "14px",
        "padding": "8px",
        "min_width": "110px",
        "background": "#18181b",
        "display": "grid",
        "gap": "2px",
    },
    ".shell.theme-light .map-node": {"background": "#f8fafc", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".map-node-title": {"font_weight": "800", "color": "#f4f4f5"},
    ".shell.theme-light .map-node-title": {"color": "#18181b"},
    ".map-arrow": {"font_size": "22px", "color": "#2dd4bf"},
    ".trace-arrow": {"font_size": "20px", "font_weight": "800", "color": "#2dd4bf"},
    ".journey-list": {"max_width": "920px", "margin": "0 auto", "width": "100%"},
    ".journey-node": {
        "position": "relative",
        "display": "grid",
        "gap": "8px",
        "padding": "16px",
        "overflow": "hidden",
    },
    ".journey-node + .journey-node": {"margin_top": "8px"},
    ".journey-step": {
        "display": "inline-flex",
        "align_items": "center",
        "justify_content": "center",
        "width": "32px",
        "height": "32px",
        "border_radius": "999px",
        "background": "rgba(45, 212, 191, 0.14)",
        "color": "#2dd4bf",
        "font_weight": "900",
    },
    ".journey-connection": {
        "text_align": "center",
        "font_size": "28px",
        "font_weight": "900",
        "color": "#2dd4bf",
    },
    ".related-entity-group": {"display": "grid", "gap": "10px", "min_width": "0"},
    ".related-entity-card": {"min_width": "0"},
    ".tabs-root": {"width": "100%"},
    ".tabs-list": {"margin_bottom": "10px"},
    ".tab-content": {"padding_top": "6px"},
    ".tab-grid": {"width": "100%"},
    ".metrics-grid": {"width": "100%"},
    ".responsive-grid": {"width": "100%"},
    ".horizontal-scroll": {"overflow_x": "auto", "width": "100%"},
    ".source-trace-scroll": {"overflow_x": "auto"},
    ".source-trace-strip": {"min_width": "fit-content"},
    ".source-card": {
        "min_width": "260px",
        "max_width": "320px",
        "display": "grid",
        "gap": "6px",
        "padding": "12px",
        "background": "#1f1f24",
    },
    ".shell.theme-light .source-card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".source-entity-card": {
        "min_width": "240px",
        "display": "grid",
        "gap": "6px",
        "padding": "12px",
        "align_self": "center",
        "background": "#1f1f24",
    },
    ".shell.theme-light .source-entity-card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".source-title": {"font_size": "16px", "font_weight": "800"},
    ".source-fact": {"font_size": "13px", "color": "#e4e4e7", "line_height": "1.4"},
    ".shell.theme-light .source-fact": {"color": "#374151"},
    ".source-fact-list": {"display": "grid", "gap": "4px"},
    ".technical-line": {
        "font_family": "Consolas, monospace",
        "font_size": "12px",
        "color": "#a1a1aa",
        "overflow_wrap": "anywhere",
    },
    ".shell.theme-light .technical-line": {"color": "#71717a"},
    ".comparison-chip": {
        "border": "1px solid rgba(45, 212, 191, 0.22)",
        "border_radius": "999px",
        "padding": "3px 8px",
        "background": "rgba(45, 212, 191, 0.1)",
        "color": "#d4d4d8",
        "font_size": "12px",
    },
    ".flow-card": {
        "display": "grid",
        "gap": "8px",
        "min_width": "0",
    },
    ".flow-accent": {"font_size": "12px", "font_weight": "800", "letter_spacing": "0.08em"},
    ".flow-accent-teal": {"color": "#2dd4bf"},
    ".flow-accent-purple": {"color": "#a78bfa"},
    ".flow-accent-amber": {"color": "#facc15"},
    ".example-card": {"display": "grid", "gap": "8px"},
    ".prompt-card": {"display": "grid", "gap": "8px"},
    ".prompt-link": {"text_decoration": "none"},
    ".button": {
        "background": "#2dd4bf",
        "color": "#0b0b0f",
        "border_radius": "12px",
        "font_weight": "700",
    },
    ".button-secondary": {
        "background": "rgba(167, 139, 250, 0.14)",
        "color": "#f4f4f5",
        "border": "1px solid rgba(167, 139, 250, 0.28)",
    },
    ".shell.theme-light .button": {"color": "#18181b"},
    ".shell.theme-light .button-secondary": {"color": "#18181b"},
    ".input": {
        "background": "#18181b",
        "border": "1px solid rgba(161, 161, 170, 0.22)",
        "color": "#f4f4f5",
    },
    ".shell.theme-light .input": {
        "background": "#ffffff",
        "border_color": "rgba(113, 113, 122, 0.24)",
        "color": "#18181b",
    },
    ".search-bar": {"width": "100%", "align_items": "center", "gap": "12px"},
    ".search-input": {
        "min_width": "0",
        "flex": "1 1 auto",
        "width": "100%",
        "font_size": "16px",
        "padding": "14px 16px",
        "height": "52px",
    },
    ".search-input::placeholder": {"color": "#71717a"},
    ".search-input:focus": {
        "border_color": "#2dd4bf",
        "box_shadow": "0 0 0 3px rgba(45, 212, 191, 0.18)",
    },
    ".search-button": {"padding": "14px 18px", "height": "52px"},
    ".search-result-card": {"min_height": "200px"},
    ".discovery-card": {"min_height": "220px"},
    ".tracking-card": {"min_height": "220px", "display": "grid", "gap": "10px", "align_content": "start"},
    ".tracking-event-card": {
        "min_height": "210px",
        "border_left": "3px solid rgba(74, 222, 128, 0.62)",
        "background": "linear-gradient(90deg, rgba(74, 222, 128, 0.06), #18181b 34%)",
    },
    ".timeline-list": {
        "position": "relative",
        "max_width": "980px",
    },
    ".page-tracking .timeline-list": {
        "padding_left": "18px",
        "border_left": "1px solid rgba(74, 222, 128, 0.28)",
    },
    ".page-tracking .tracking-event-card": {
        "min_height": "auto",
        "padding": "18px 20px",
        "border_left": "3px solid rgba(74, 222, 128, 0.72)",
        "border_radius": "0 8px 8px 0",
    },
    ".tracking-document-card": {"min_height": "230px"},
    ".report-card": {"min_height": "210px", "display": "grid", "gap": "10px", "align_content": "start"},
    ".report-section-card": {"min_height": "190px", "display": "grid", "gap": "8px", "align_content": "start"},
    ".help-card": {"min_height": "150px", "display": "grid", "gap": "8px", "align_content": "start"},
    ".next-step-card": {"min_height": "185px", "display": "grid", "gap": "10px", "align_content": "start"},
    ".button-disabled": {"opacity": "0.55", "cursor": "not-allowed"},
    ".page-investigation .investigation-card": {"border_left": "3px solid rgba(45, 212, 191, 0.38)"},
    ".page-investigation .summary-card": {"border_top": "2px solid rgba(45, 212, 191, 0.32)"},
    ".page-library .tracking-document-card": {
        "border_left": "3px solid rgba(167, 139, 250, 0.58)",
        "background": "linear-gradient(90deg, rgba(167, 139, 250, 0.06), #18181b 34%)",
    },
    ".page-library .report-section-card": {"border_top": "2px solid rgba(167, 139, 250, 0.32)"},
    ".page-reports .report-card": {
        "background": "transparent",
        "border_left": "3px solid rgba(251, 146, 60, 0.46)",
        "border_top": "0",
        "border_right": "0",
        "border_bottom": "0",
        "border_radius": "0",
        "padding": "8px 0 8px 18px",
    },
    ".page-reports .report-section-card": {
        "background": "transparent",
        "border_top": "0",
        "border_right": "0",
        "border_bottom": "0",
        "border_left": "3px solid rgba(251, 146, 60, 0.34)",
        "border_radius": "0",
        "padding": "6px 0 6px 18px",
    },
    ".page-reports .story-summary": {"font_size": "17px", "line_height": "1.75", "max_width": "900px"},
    ".page-ecosystem .source-card, .page-ecosystem .card": {"border_left": "3px solid rgba(96, 165, 250, 0.34)"},
    ".page-project .flow-card, .page-project .help-card": {"border_left": "3px solid rgba(161, 161, 170, 0.42)"},
    ".investigation-welcome": {"padding": "42px 34px"},
    ".investigation-welcome-search": {"max_width": "860px", "margin_top": "22px"},
    ".investigation-error": {"border_left": "4px solid rgba(251, 113, 133, 0.56)"},
    ".public-demo-card": {
        "border_left": "3px solid rgba(45, 212, 191, 0.38)",
        "background": "linear-gradient(90deg, rgba(45, 212, 191, 0.05), #18181b 32%)",
    },
    ".explorer-panel": {
        "border": "1px solid rgba(161, 161, 170, 0.10)",
        "border_radius": "16px",
        "padding": "16px",
        "background": "#18181b",
        "display": "grid",
        "gap": "12px",
    },
    ".shell.theme-light .explorer-panel": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".explorer-category-button": {
        "border": "1px solid rgba(113, 113, 122, 0.22)",
        "background": "#1f1f24",
        "color": "#f4f4f5",
        "padding": "8px 12px",
        "height": "40px",
        "font_weight": "700",
    },
    ".explorer-category-button-active": {
        "border_color": "#a78bfa",
        "background": "rgba(167, 139, 250, 0.16)",
        "color": "#f4f4f5",
        "box_shadow": "0 0 0 1px rgba(167, 139, 250, 0.18)",
    },
    ".shell.theme-light .explorer-category-button": {"background": "#ffffff", "color": "#18181b"},
    ".shell.theme-light .explorer-category-button-active": {"background": "rgba(167, 139, 250, 0.12)", "color": "#18181b"},
    ".search-chip": {
        "border": "1px solid rgba(113, 113, 122, 0.2)",
        "border_radius": "999px",
        "padding": "8px 12px",
        "background": "#1f1f24",
        "color": "#f4f4f5",
    },
    ".search-chip-text": {"font_size": "13px", "font_weight": "600"},
    ".shell.theme-light .search-chip": {"background": "#ffffff"},
    ".shell.theme-light .search-chip-text": {"color": "#18181b"},
    ".shell.theme-light .badge": {"background": "rgba(45, 212, 191, 0.12)", "color": "#0f766e", "border_color": "rgba(45, 212, 191, 0.24)"},
    ".shell.theme-light .badge-teal": {"background": "rgba(45, 212, 191, 0.12)", "color": "#0f766e", "border_color": "rgba(45, 212, 191, 0.24)"},
    ".shell.theme-light .badge-purple": {"background": "rgba(167, 139, 250, 0.12)", "color": "#6d28d9", "border_color": "rgba(167, 139, 250, 0.24)"},
    ".shell.theme-light .badge-amber": {"background": "rgba(250, 204, 21, 0.12)", "color": "#b45309", "border_color": "rgba(250, 204, 21, 0.24)"},
    ".shell.theme-light .mini-pill": {"background": "rgba(45, 212, 191, 0.08)", "color": "#0f766e", "border_color": "rgba(45, 212, 191, 0.18)"},
    ".shell.theme-light .mini-pill-purple": {"background": "rgba(167, 139, 250, 0.08)", "color": "#6d28d9", "border_color": "rgba(167, 139, 250, 0.18)"},
    ".shell.theme-light .story-chip": {"background": "rgba(167, 139, 250, 0.08)", "color": "#6d28d9", "border_color": "rgba(167, 139, 250, 0.18)"},
    ".shell.theme-light .prompt-chip": {"background": "rgba(45, 212, 191, 0.08)", "color": "#0f766e", "border_color": "rgba(45, 212, 191, 0.18)"},
    ".shell.theme-light .comparison-chip": {"background": "rgba(45, 212, 191, 0.08)", "color": "#0f766e", "border_color": "rgba(45, 212, 191, 0.18)"},
    ".shell.theme-light .evidence-trust": {"background": "rgba(250, 204, 21, 0.1)", "color": "#92400e", "border_color": "rgba(250, 204, 21, 0.24)"},
    ".shell.theme-light .canonical-link-box": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".shell.theme-light .flow-card": {"background": "#ffffff", "border_color": "rgba(113, 113, 122, 0.18)"},
    ".shell.theme-light .flow-accent-teal": {"color": "#0f766e"},
    ".shell.theme-light .flow-accent-purple": {"color": "#6d28d9"},
    ".shell.theme-light .flow-accent-amber": {"color": "#b45309"},
    ".loading-shell": {"min_height": "100vh"},
    ".loading-skeleton-hero": {"display": "grid", "gap": "14px"},
    ".loading-skeleton-card": {"min_height": "210px", "display": "grid", "gap": "10px", "align_content": "start"},
    ".loading-skeleton-line": {
        "height": "12px",
        "border_radius": "999px",
        "background": "linear-gradient(90deg, rgba(45, 212, 191, 0.18), rgba(228, 228, 231, 0.14), rgba(45, 212, 191, 0.18))",
        "background_size": "200% 100%",
        "animation": "loading-pulse 1.6s ease-in-out infinite",
    },
    ".loading-skeleton-line-medium": {"width": "68%"},
    ".loading-skeleton-line-short": {"width": "42%"},
    ".not-found-hero": {
        "grid_template_columns": "minmax(0, 1.35fr) minmax(240px, 0.7fr)",
        "align_items": "center",
        "width": "100%",
    },
    ".not-found-illustration": {"position": "relative", "display": "grid", "justify_items": "center", "padding": "12px"},
    ".not-found-document-card": {
        "width": "220px",
        "min_height": "260px",
        "border": "1px solid rgba(161, 161, 170, 0.18)",
        "border_radius": "16px",
        "padding": "18px",
        "background": "linear-gradient(180deg, rgba(45, 212, 191, 0.12), rgba(24, 24, 27, 0.92))",
        "display": "grid",
        "gap": "12px",
        "box_shadow": "0 18px 50px rgba(0, 0, 0, 0.22)",
    },
    ".shell.theme-light .not-found-document-card": {
        "background": "linear-gradient(180deg, rgba(45, 212, 191, 0.12), #ffffff)",
        "border_color": "rgba(113, 113, 122, 0.18)",
    },
    ".not-found-document-tab": {"width": "72px", "height": "10px", "border_radius": "999px", "background": "rgba(45, 212, 191, 0.52)"},
    ".not-found-document-body": {"display": "grid", "gap": "10px"},
    ".not-found-document-line": {"height": "12px", "border_radius": "999px", "background": "rgba(212, 212, 216, 0.24)"},
    ".not-found-document-line-medium": {"width": "76%"},
    ".not-found-document-line-short": {"width": "52%"},
    ".not-found-badge": {
        "position": "absolute",
        "right": "18px",
        "bottom": "18px",
        "padding": "7px 12px",
        "border_radius": "999px",
        "background": "rgba(250, 204, 21, 0.16)",
        "border": "1px solid rgba(250, 204, 21, 0.28)",
        "color": "#fde68a",
        "font_size": "12px",
        "font_weight": "800",
    },
    ".empty-entry-card": {"min_height": "220px", "display": "grid", "gap": "10px", "align_content": "start"},
    ".empty-entry-card .example-card": {"padding": "10px", "min_height": "auto"},
    ".investigation-empty-grid": {"align_items": "stretch"},
    ".home-lower-layout": {
        "display": "grid",
        "grid_template_columns": "minmax(0, 1.35fr) minmax(340px, 0.85fr)",
        "gap": "24px",
        "align_items": "start",
    },
    ".home-lower-layout .page-section": {
        "min_width": "0",
    },
    "@keyframes loading-pulse": {
        "0%": {"background_position": "0% 50%", "opacity": "0.72"},
        "50%": {"background_position": "100% 50%", "opacity": "1"},
        "100%": {"background_position": "0% 50%", "opacity": "0.72"},
    },
    "@keyframes document-pulse": {
        "0%": {"background": "#ccfbf1"},
        "35%": {"background": "#ecfeff"},
        "100%": {"background": "#ffffff"},
    },
    "@media (max-width: 1100px)": {
        ".reading-document-workspace": {"grid_template_columns": "1fr"},
        ".reading-document-side": {"position": "static"},
    },
    "@media (max-width: 900px)": {
        ".shell-main": {"margin_left": "0"},
        ".shell.sidebar-collapsed .shell-main": {"margin_left": "0"},
        ".app-sidebar": {"display": "none"},
        ".nav-inner": {"flex_wrap": "wrap"},
        ".nav-links": {"justify_content": "flex-start"},
        ".investigation-layout": {"grid_template_columns": "1fr"},
        ".context-panel": {"position": "static"},
        ".investigation-sidebar": {"max_height": "none"},
        ".search-input": {"min_width": "0"},
        ".search-bar": {"flex_direction": "column", "align_items": "stretch"},
        ".search-button": {"width": "100%"},
        ".home-lower-layout": {"grid_template_columns": "1fr"},
        ".official-document-layout": {"grid_template_columns": "1fr"},
        ".document-side-column": {"position": "static"},
        ".not-found-hero": {"grid_template_columns": "1fr"},
        ".reading-context-bar": {"grid_template_columns": "1fr 1fr", "align_items": "start"},
        ".topic-document-first-layout": {"grid_template_columns": "1fr"},
        ".topic-context-rail": {"display": "none"},
        ".topic-source-panel": {"position": "static", "max_height": "72vh"},
        ".footer-grid": {"grid_template_columns": "1fr"},
        ".topic-evidence-grid": {"grid_template_columns": "1fr"},
        ".reference-strip": {"grid_template_columns": "1fr"},
    },
}

style.setdefault(".site-footer", {}).update({"padding": "26px 22px 18px"})
style.setdefault(".footer-grid", {}).update({"grid_template_columns": "repeat(2, minmax(0, 1fr))"})
style.setdefault(".topic-source-panel", {}).update({"position": "relative"})
style.setdefault(".topic-pdf-frame", {}).update({"min_height": "76vh"})
style.setdefault(".official-document-pdf-frame", {}).update({"min_height": "78vh"})
style.setdefault(".reading-document-workspace", {}).update({"grid_template_columns": "minmax(0, 1.7fr) minmax(300px, 0.78fr)"})
style.setdefault(".reading-document-side", {}).update({"position": "sticky"})

style.update({
    ".page-laboratory": {"max_width": "1180px"},
    ".laboratory-panel": {"display": "grid", "gap": "12px", "padding": "16px"},
    ".laboratory-tabs-list": {"display": "flex", "flex_wrap": "wrap", "gap": "6px"},
    ".laboratory-entity-card": {"display": "grid", "gap": "6px", "padding": "12px"},
    ".laboratory-progress-panel": {"display": "grid", "gap": "8px"},
    ".laboratory-progress": {"width": "100%"},
})
